language: python

sudo: false

python:
    - 2.7

env:
    - TOXENV=py27-django17
    - TOXENV=py27-django18
    - TOXENV=py33-django17
    - TOXENV=py33-django18
    - TOXENV=py34-django17
    - TOXENV=py34-django18

install:
    - pip install tox coverage

before_script:
    - psql -c 'CREATE DATABASE oscar_stores;' -U postgres
    - psql -c 'CREATE EXTENSION postgis;' -U postgres -d oscar_stores
    - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d oscar_stores

script:
    - tox
